const express = require("express");
const dotenv = require("dotenv").config();
const { GoogleGenerativeAI } = require("@google/generative-ai");

const genAi = new GoogleGenerativeAI(process.env.GEMINI_API);
const model = genAi.getGenerativeModel({model: "gemini-1.5-flash"});

const app = express();

const generateContent = async (req, res) => {
    const result = "";

    try {
        const prompt = `
        You are in task of generating websites. Generate an HTML file with valid HTML, CSS, and JS for the route ${req.path}. Do not give any comments about this file. Simply respond with the file's contents and nothing else. Additionally, do not include any markdown in this answer.
        Try to make the website look decently professional. In addition, the /home and / routes should have information of the website being generated by AI. The website should also be complete and say nothing along the lines of "you can add more if you like."
        `
        const answer = await model.generateContent(prompt);
        const response = await answer.response;
        const result = response.text();
        console.log(result)
        res.send(result)
    }
    catch (err) {
        console.log(err);
        res.send("unexpected error.")
    }
}

app.use(generateContent)

app.listen(3000, () => {
    console.log("Listening on 3000")
})